general:
  productiveBranch: 'whitesource'
  buildTool: 'yarn'

  whitesourceProductName: 'DIST - cloud-sdk-js-os'
  whitesourceUserTokenCredentialsId: 'Whitesource_User_Token'

steps:
  whitesourceExecuteScan:
    orgAdminUserTokenCredentialsId: 'whitesource-orgToken'
